### ISSUE TITLE
Server: Рефакторинг server/index.ts

### ISSUE THREAD

**Issue by lFandoriNl** [lFandoriNl/monopoly#12]
Нужно отрефатчить лапшу `server/index.ts`
Предлагаю создать папочку `server/src/controllers` и накидать с помощью этой либы контроллеров:
`SessionController, GameController, GameEventsController` которые уже будут обрабатывать соответсвующие им собщения:
`session.recovery.request, game.create, game.events.roll-dice` и тд.
https://github.com/typestack/socket-controllers

**Comment by lFandoriNl** [comment]
Если либа как то не зайдет то пока упустим ее и сделаем без нее

**Comment by nevstafev** [comment]
Хочу взять эту задачу
