### ISSUE TITLE
Client: Баг отображения кнопки покупки до завершения анимации

### ISSUE THREAD

**Issue by lFandoriNl** [lFandoriNl/monopoly#31]
Сейчас если кинуть кубики то кнопка **Купить** мгновенно показывается.

Нужно что бы анимация проигралась до конца и только потом отображался ActionsPopup

Колбек который вызывается по окончанию анимации:
`client/src/game/board/chip/chip.tsx:27`

**Comment by alexey-pd** [comment]
такс, видел вызов в коде - подкручу ещё анимации :octocat:

**Comment by alexey-pd** [comment]
https://github.com/lFandoriNl/monopoly/pull/40 🎮
