### ISSUE TITLE
Client: ошибка ссылки без id

### ISSUE THREAD

**Issue by alexey-pd** [lFandoriNl/monopoly#38]
при переходе на роут /game без указания id - отображается окно создания в пустоту,
а лучше вести на экран выбора количества игроков и генерацию игрового id :) 

![Screenshot 2021-01-11 at 00 26 37](https://user-images.githubusercontent.com/12380196/104135894-b9634f00-53a3-11eb-89a4-b6ced1e0af09.png)

актуально / мне взять?

**Comment by lFandoriNl** [comment]
Да и также если есть id но этой игры нету в базе то тоже редиректить на создание игры

**Comment by lFandoriNl** [comment]
Назначил на тебя 👍

**Comment by alexey-pd** [comment]
https://github.com/lFandoriNl/monopoly/pull/41

**Comment by lFandoriNl** [comment]
@alexey-pd Вот где определяется есть ли игра `server/src/controllers/session-controller.ts:37`

Если игры нету то можно слать какой то ивент по которому уже на фронте будем редиректить

**Comment by alexey-pd** [comment]
добавил чек с события
